[phases.setup]
nixPkgs = ["...", "openjdk21"]

[phases.build]
cmds = ["./gradlew bootJar --no-daemon"]

[start]
cmd = "java -Dspring.profiles.active=prod -jar build/libs/*.jar"

[variables]
PORT = "8080"