spring:
  application:
    name: meowtown
  
  profiles:
    active: dev
    
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:meowtown-super-secret-key-for-development-only-please-change-in-production}
  expiration: ${JWT_EXPIRES_IN:604800} # 7 days in seconds

# AWS Configuration
aws:
  s3:
    bucket: ${AWS_S3_BUCKET:meowtown-images}
    region: ${AWS_REGION:ap-northeast-2}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}

# API Configuration
api:
  version: v1
  cors:
    allowed-origins: ${CORS_ORIGIN:http://localhost:3000,https://meowtown-front.vercel.app}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    
# Rate Limiting
rate-limit:
  general:
    requests: 100
    per: 60 # seconds
  upload:
    requests: 20
    per: 60
    
# File Upload Settings
file:
  upload:
    max-size: 10485760 # 10MB in bytes
    allowed-types: image/jpeg,image/png,image/webp,image/gif
    thumbnail:
      size: 300
    medium:
      size: 600

# Logging Configuration
logging:
  level:
    com.meowtown: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
server:
  port: ${PORT:8080}
  # Removed context-path - using full paths in controllers
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized