spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:5}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      
  data:
    redis:
      # Railway Redis configuration
      host: ${REDIS_HOST:${REDISHOST:localhost}}
      port: ${REDIS_PORT:${REDISPORT:6379}}
      password: ${REDIS_PASSWORD:${REDISPASSWORD:}}
      database: 0
      ssl: ${REDIS_SSL:false}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
      
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        
  # Additional production settings for Railway  
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    com.meowtown: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Production security settings
server:
  port: ${PORT:8080}
  ssl:
    enabled: ${SSL_ENABLED:false}
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
  shutdown: graceful
  tomcat:
    max-threads: ${SERVER_MAX_THREADS:200}
    accept-count: ${SERVER_ACCEPT_COUNT:100}

# Strict CORS in production
cors:
  allowed-origins: ${CORS_ORIGIN:https://your-frontend-domain.com}

# Production-specific rate limiting (stricter)
rate-limit:
  general:
    requests: 60
    per: 60
  upload:
    requests: 10
    per: 60

# Railway-specific configurations
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      show-components: never
  health:
    redis:
      enabled: true
    db:
      enabled: true