spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/meowtown_dev}
    username: ${DB_USERNAME:meowtown}
    password: ${DB_PASSWORD:meowtown123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  h2:
    console:
      enabled: false

logging:
  level:
    com.meowtown: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Development-specific settings
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:3001
    - http://127.0.0.1:3000

# Enable debug mode
debug: false

# Development JWT (shorter expiration for testing)
jwt:
  expiration: 86400 # 1 day in seconds